// Code generated by protoc-gen-go.
// source: model/message.proto
// DO NOT EDIT!

/*
Package model is a generated protocol buffer package.

It is generated from these files:
	model/message.proto
	model/test.proto

It has these top-level messages:
	Request
	Response
	Error
	Hello
	World
*/
package model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ErrorType int32

const (
	Error_APPLICATION   ErrorType = 0
	Error_SERIALIZATION ErrorType = 1
	Error_PROTOCOL      ErrorType = 2
	Error_NETWORK       ErrorType = 3
	Error_SERVER_PANIC  ErrorType = 4
	Error_TIMEOUT       ErrorType = 5
	Error_BAD_METHOD    ErrorType = 6
)

var ErrorType_name = map[int32]string{
	0: "APPLICATION",
	1: "SERIALIZATION",
	2: "PROTOCOL",
	3: "NETWORK",
	4: "SERVER_PANIC",
	5: "TIMEOUT",
	6: "BAD_METHOD",
}
var ErrorType_value = map[string]int32{
	"APPLICATION":   0,
	"SERIALIZATION": 1,
	"PROTOCOL":      2,
	"NETWORK":       3,
	"SERVER_PANIC":  4,
	"TIMEOUT":       5,
	"BAD_METHOD":    6,
}

func (x ErrorType) String() string {
	return proto.EnumName(ErrorType_name, int32(x))
}
func (ErrorType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

type Request struct {
	Name      string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Signature string `protobuf:"bytes,2,opt,name=Signature" json:"Signature,omitempty"`
	RawBody   []byte `protobuf:"bytes,3,opt,name=RawBody,proto3" json:"RawBody,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Response struct {
	// Types that are valid to be assigned to Body:
	//	*Response_Error
	//	*Response_RawOK
	Body      isResponse_Body `protobuf_oneof:"Body"`
	Signature string          `protobuf:"bytes,3,opt,name=Signature" json:"Signature,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type isResponse_Body interface {
	isResponse_Body()
}

type Response_Error struct {
	Error *Error `protobuf:"bytes,1,opt,name=Error,oneof"`
}
type Response_RawOK struct {
	RawOK []byte `protobuf:"bytes,2,opt,name=RawOK,proto3,oneof"`
}

func (*Response_Error) isResponse_Body() {}
func (*Response_RawOK) isResponse_Body() {}

func (m *Response) GetBody() isResponse_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Response) GetError() *Error {
	if x, ok := m.GetBody().(*Response_Error); ok {
		return x.Error
	}
	return nil
}

func (m *Response) GetRawOK() []byte {
	if x, ok := m.GetBody().(*Response_RawOK); ok {
		return x.RawOK
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Response) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Response_OneofMarshaler, _Response_OneofUnmarshaler, _Response_OneofSizer, []interface{}{
		(*Response_Error)(nil),
		(*Response_RawOK)(nil),
	}
}

func _Response_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Response)
	// Body
	switch x := m.Body.(type) {
	case *Response_Error:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Error); err != nil {
			return err
		}
	case *Response_RawOK:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.RawOK)
	case nil:
	default:
		return fmt.Errorf("Response.Body has unexpected type %T", x)
	}
	return nil
}

func _Response_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Response)
	switch tag {
	case 1: // Body.Error
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Error)
		err := b.DecodeMessage(msg)
		m.Body = &Response_Error{msg}
		return true, err
	case 2: // Body.RawOK
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.Body = &Response_RawOK{x}
		return true, err
	default:
		return false, nil
	}
}

func _Response_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Response)
	// Body
	switch x := m.Body.(type) {
	case *Response_Error:
		s := proto.Size(x.Error)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_RawOK:
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.RawOK)))
		n += len(x.RawOK)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Error struct {
	Message string    `protobuf:"bytes,1,opt,name=Message" json:"Message,omitempty"`
	Type    ErrorType `protobuf:"varint,2,opt,name=Type,enum=model.ErrorType" json:"Type,omitempty"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*Request)(nil), "model.Request")
	proto.RegisterType((*Response)(nil), "model.Response")
	proto.RegisterType((*Error)(nil), "model.Error")
	proto.RegisterEnum("model.ErrorType", ErrorType_name, ErrorType_value)
}

func init() { proto.RegisterFile("model/message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x5c, 0x91, 0x5d, 0x6b, 0xfa, 0x30,
	0x14, 0xc6, 0xad, 0xb6, 0xbe, 0x1c, 0xfb, 0xf7, 0x1f, 0xcf, 0x60, 0xf4, 0x62, 0x17, 0x43, 0x36,
	0xd8, 0x55, 0x07, 0xee, 0x13, 0x54, 0x0d, 0x18, 0xd4, 0xa6, 0xc4, 0xb8, 0xc1, 0x6e, 0xa4, 0xc3,
	0x20, 0x83, 0x69, 0xba, 0xb6, 0x32, 0xfc, 0x72, 0xfb, 0x6c, 0x6b, 0x53, 0x65, 0x2f, 0x77, 0x79,
	0x9e, 0x5f, 0x4e, 0x9e, 0xe7, 0x10, 0xb8, 0xd8, 0xe9, 0x8d, 0x7a, 0xbb, 0xdf, 0xa9, 0x2c, 0x8b,
	0xb7, 0xca, 0x4f, 0x52, 0x9d, 0x6b, 0x74, 0x8c, 0x39, 0x58, 0x41, 0x4b, 0xa8, 0xf7, 0x83, 0xca,
	0x72, 0x44, 0xb0, 0xc3, 0x78, 0xa7, 0x3c, 0xeb, 0xda, 0xba, 0xeb, 0x08, 0x73, 0xc6, 0x2b, 0xe8,
	0x2c, 0x5f, 0xb7, 0xfb, 0x38, 0x3f, 0xa4, 0xca, 0xab, 0x1b, 0xf0, 0x6d, 0xa0, 0x57, 0x0c, 0xc7,
	0x1f, 0x23, 0xbd, 0x39, 0x7a, 0x8d, 0x82, 0xb9, 0xe2, 0x2c, 0x07, 0x7b, 0x68, 0x0b, 0x95, 0x25,
	0x7a, 0x9f, 0x29, 0xbc, 0x01, 0x87, 0xa6, 0xa9, 0x4e, 0xcd, 0xc3, 0xdd, 0xa1, 0xeb, 0x9b, 0x64,
	0xdf, 0x78, 0xd3, 0x9a, 0xa8, 0x20, 0x5e, 0x82, 0x53, 0x0c, 0xf3, 0x99, 0x49, 0x71, 0x4b, 0xdf,
	0xc8, 0xdf, 0x0d, 0x1a, 0x7f, 0x1a, 0x8c, 0x9a, 0x60, 0x9b, 0xbc, 0x4f, 0xeb, 0x14, 0x52, 0x76,
	0x5a, 0x54, 0x8b, 0x9e, 0x16, 0x39, 0x4b, 0xbc, 0x05, 0x5b, 0x1e, 0x93, 0x6a, 0x8d, 0xde, 0xb0,
	0xff, 0xb3, 0x86, 0x9f, 0x17, 0x40, 0x18, 0x3c, 0xc8, 0xc1, 0x2e, 0x15, 0xfe, 0x87, 0x6e, 0x10,
	0x45, 0x73, 0x36, 0x0e, 0x24, 0xe3, 0x21, 0xa9, 0x61, 0x1f, 0xfe, 0x2d, 0xa9, 0x60, 0xc1, 0x9c,
	0x3d, 0x57, 0x96, 0x85, 0x2e, 0xb4, 0x23, 0xc1, 0x25, 0x1f, 0xf3, 0x39, 0xa9, 0x63, 0x17, 0x5a,
	0x21, 0x95, 0x4f, 0x5c, 0xcc, 0x48, 0x03, 0x09, 0xb8, 0xc5, 0xed, 0x47, 0x2a, 0xd6, 0x51, 0x10,
	0xb2, 0x31, 0xb1, 0x4b, 0x2c, 0xd9, 0x82, 0xf2, 0x95, 0x24, 0x0e, 0xf6, 0x00, 0x46, 0xc1, 0x64,
	0xbd, 0xa0, 0x72, 0xca, 0x27, 0xa4, 0xf9, 0xd2, 0x34, 0xbf, 0xf2, 0xf0, 0x15, 0x00, 0x00, 0xff,
	0xff, 0x0e, 0xee, 0x1b, 0x49, 0xac, 0x01, 0x00, 0x00,
}
